<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuraCommerce.Orders.Application\AuraCommerce.Orders.Application.csproj" />
    <ProjectReference Include="..\AuraCommerce.Orders.Infrastructure\AuraCommerce.Orders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
